---

language: ruby
sudo: required

services:
  - docker

env:
  - DISTRIB=debian:stretch
  - DISTRIB=ubuntu:trusty

install:
  - gem install serverspec

before_script:
  - mkdir "$HOME/bin"
  - curl -Lso "$HOME/bin/shellcheck" https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.3/shellcheck
  - chmod +x "$HOME/bin/shellcheck"
  - export PATH=$PATH:$HOME/bin

script:
  - make test
